name: 'Setup Python environment'

description: 'A thin wrapper around setup-miniconda to setup python environments.'


inputs:
  exec-shell:
    description: 'Name of the execution shell'
    default: 'bash -l {0}'
  dvlpy-environment:
    description: 'Name of the dvlpy environment'
    default: 'dvlpy'
  environment-file:
    description: 'Environment file used to install dependencies'
    required: true
  cache-number:
    description: 'Cache number for caching artifacts'
    default: 0
  python-version:
    description: 'Python version used'
    default: '3.10'
  install-package:
    description: 'Install package into environment'
    default: true
  run-tests:
    description: 'Run unit tests for this package'
    default: true
  package-variant:
    description: 'Variant of package to install'
    default: '[dev]'
  pycov-module:
    description: 'Modules for which coverage reporting is generated'
    default: 'dvl'
  package-path:
    description: 'Path to the package directory'
    default: '.'
  tests-path:
    description: 'Path to the unit test directory'
    default: 'tests'
  build-docs:
    description: 'Build Sphinx documentation'
    default: false

runs:
  using: "composite"
  steps:
    - name: Cache conda environment
      uses: actions/cache@v2
      env:
        CACHE_NUMBER: ${{ inputs.cache-number }}
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-py-${{ inputs.python-version }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles(inputs.environment-file) }}
    - name: Setup python environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ inputs.python-version }}
        miniforge-variant: Mambaforge
        miniforge-version:  latest
        use-mamba: true
        mamba-version: "*"
        activate-environment: ${{ inputs.dvlpy-environment }}
        environment-file: ${{ inputs.environment-file }}
        channels: conda-forge
        channel-priority: strict
        use-only-tar-bz2: true
    - name: Install package
      if: ${{ inputs.install-package }}
      run: |
        echo "::group::Install package into environment"
        conda activate ${{ inputs.dvlpy-environment }}
        cd ${{ inputs.package-path }}
        python -m pip install .
        echo "::endgroup::"
      shell: bash -l {0}
    - name: Run tests
      if: ${{ inputs.run-tests }}
      run: |
        echo "::group::Install test dependencies in environment"
        conda activate ${{ inputs.dvlpy-environment }}
        mamba install pytest pytest-cov
        cd ${{ inputs.package-path }}
        echo "::endgroup::"
        python -m pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=${{ inputs.pycov-module }} ${{ inputs.tests-path }} | tee pytest-coverage.txt
        cat pytest-coverage.txt
      shell: bash -l {0}
    - name: Unit test coverage report
      if: ${{ inputs.run-tests }}
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-coverage-path: ${{ inputs.package-path }}/pytest-coverage.txt
        junitxml-path: ${{ inputs.package-path }}/pytest.xml
        title: dvl-core test coverage
        badge-title: dvlcore
        junitxml-title: dvl-core coverage summary
    - name: Run Sphinx
      if: ${{ inputs.build-docs }}
      run: |
        echo "::group::Install sphinx dependencies"
        conda activate dvlpy
        mamba install sphinx sphinx_rtd_theme
        cd ${{ inputs.package-path }}/docs/
        echo "::endgroup::"
        make html
        touch build/html/.nojekyll
      shell: bash -l {0}
    - name: Deploy docs
      if: github.event_name == 'push' && ${{ inputs.build-docs }}
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: ${{ inputs.package-path }}/docs/build/html
        SINGLE_COMMIT: true
